name: Plugin Asset Update

on:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'

jobs:
  asset-update:
    name: Asset Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: WordPress.org Plugin Asset Update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: refaxination
